language: minimal

branches:
  only:
  - master

jobs:
  include:
    - name: Linux | x86_64 + i686 | Python 3.6
      arch: amd64
      language: python
      python: 3.6
      services: docker
      env: PYTHON=python

    - name: Linux | arm64 | Python 3.6
      arch: arm64
      language: python
      python: 3.6
      services: docker
      arch: arm64
      env: PYTHON=python

    

  allow_failures:
    # must repeat the s390x job above exactly to match
    - *linux_s390x_36

install: $PYTHON -m pip install -r requirements-dev.txt

script: $PYTHON ./bin/run_tests.py
